apiVersion: v1 #[1. API의 버전 정보]
kind: ConfigMap #[2. 리소스의 종류]
metadata:
  name: nginx-config #[3. 리소스의 이름]
data:
  default.conf: |
    upstream httpd-service{
      server httpd-service:80;
    }

    server{
      listen 80;
      location / {
        proxy_pass http://httpd_upstream;
      }
    }
