apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.images.repository }}:{{ .Values.httpd.images.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
         - mountPath: /etc/nginx/conf.d/default.conf
           name: nginx-config
           subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
