apiVersion: apps/v1 #[1. API의 버전 정보]
kind: Deployment #[2. 리소스의 종류]
metadata:
  name: httpd-deployment #[3. 리소스의 이름]
spec:
  replicas: 1  #[4. 리소스의 상세 정보]
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd 
    spec: 
      containers: 
      - name: httpd
        image: httpd
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: 15m 
            memory: 10Mi
          limits:
            cpu: 15m
            memory: 10Mi

---
apiVersion: v1
kind: Service
metadata: 
  name: httpd-service
spec:
  selector:
   app: httpd
  ports: 
  - protocol: TCP
    port: 80 
    targetPort: 80
  type: ClusterIP
            
